#!/bin/sh
# DEBIAN/preinst

# Check for and build list (PACKAGES) of missing required packages
echo "Checking required packages..."
for package in python3 python3-pip python3-venv python3-dev libusb-1.0-0-dev libudev-dev
do
    PKG_OK=$(dpkg-query -W -f='${Status}\n' $package | grep "install ok installed")
    if test -z "$PKG_OK"; then
      PACKAGES="${PACKAGES} $package"
    fi
done

# Exit on error
set -e

# Install required packages
if test "$PACKAGES"; then
    echo "Installing required packages..."
    apt-get --yes install ${PACKAGES}
fi

echo "Done."
